# fly.toml
app = "docesludb"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true

  [[http_service.checks]]
    grace_period = "1s"
    interval = "10s"
    method = "GET"
    path = "/health"
    timeout = "2s"